### ISSUE TITLE
BGCOLOR and FGCOLOR reversed?

### ISSUE THREAD

**Issue by AXDOOMER** [nukeykt/pcdoom#3]
Context: https://github.com/nukeykt/pcdoom/blob/master/D_MAIN.C#L24
```
#define	BGCOLOR		4
#define	FGCOLOR		7
```
According to the color chart on this page: http://www.brackeen.com/vga/basics.html

4 is red and 7 is light gray, but when displayed the banner is light gray and the text is red. 

Maybe there is also a problem with this?: https://github.com/nukeykt/pcdoom/blob/master/D_MAIN.C#L553

Some color combinations make the text blink, for example when you use the light color text. 

I don't know if you have reverse-engineered this and if it's actually a vanilla Doom bug. 

EDIT:

Documentation:
http://www.dsi.unive.it/~franz/c_program/advcw3.htm
```
/* bits 0 - 2 specify the foreground color */
/* bit 3 specifies the intensity, 0 = normal */
/* bits 4 - 6 specify the background color */
/* bit 7 specifies blinking, 0 = non-blinking*/
```

**Comment by nukeykt** [comment]
I've already fixed this bug in PCDoom v2. This is not original Doom bug. These defines are present in Linuxdoom sources and matches to Final Doom ones.

**Comment by AXDOOMER** [comment]
Where is PCDoom v2? I hope I forked the good one...

I found some documentation, I'll leave it there for me.
http://www.dsi.unive.it/~franz/c_program/advcw3.htm
```
/* bits 0 - 2 specify the foreground color */
/* bit 3 specifies the intensity, 0 = normal */
/* bits 4 - 6 specify the background color */
/* bit 7 specifies blinking, 0 = non-blinking*/
```

**Comment by nukeykt** [comment]
I haven't published it yet. I'll publish it soon.

**Comment by AXDOOMER** [comment]
Cool! I'm pleased to see that you still working on enhancing this port.

**Comment by AXDOOMER** [comment]
> I've already fixed this bug in PCDoom v2.

Closing.
