### ISSUE TITLE
PCDOOMv2: Still looking for the HELP lump

### ISSUE THREAD

**Issue by AXDOOMER** [nukeykt/pcdoom#7]
When I run The Ultimate Doom and press F1 or Read This! then it crash because HELP cannot be found. I believe HELP2 is still in the WAD and that's the lump that it's supposed to load.

**Comment by nukeykt** [comment]
PCDoom v2 behaves like Alternate Final Doom executable. I'm planning to support various versions down to 1.666.

**Comment by AXDOOMER** [comment]
I have a copy of this Doom2.exe (CRC: 503d9154) and this bug does not occur.

**Comment by nukeykt** [comment]
Are you sure? I got "W_GetNumForName: HELP not found!" with the same EXE and Ultimate Doom IWAD.

**Comment by AXDOOMER** [comment]
Right, I was using the Ultimate Doom executable rather than the Alternative Final Doom executable.
