### ISSUE TITLE
Add MUS support (better music support without DMX)

### ISSUE THREAD

**Issue by AXDOOMER** [nukeykt/pcdoom#9]
MIDI files already play, but it would be nice to have support for MUS. Ports like Chocolate-Doom, [doomnew](https://bitbucket.org/maraakate/doomnew-for-dos) and [CDoom](https://sourceforge.net/projects/cdoom207/) already have support for MUS. Chocolate-Doom uses MUS2MIDI, CDoom uses [MUSLIB 1.8](http://www.fit.vutbr.cz/~arnost/muslib/) (dunno were Carlos got v1.8) and doomnew uses DMX (which can't be used for legal reasons). There must be a way to add it for the ASS. 

The other day, I ran a PWAD with MIDI files in it and it played correctly. The OPL support was very poor and GUS worked through MIDI. The GUS bug with repeating percussions was there, but the instruments sounded like general midi. I don't know if there is a way to improve OPL synthesis with ASS though.

**Comment by AXDOOMER** [comment]
The reason why OPL sounds so poorly may be because PCDOOM doesn't use the GENMIDI lump.

**Comment by nukeykt** [comment]
Yeah. PCDoom v2 has GENMIDI to TMB converter, so now it sounds better

**Comment by AXDOOMER** [comment]
I just checked PCDOOM v2 and everything works! (except the PC speaker) 

Great job!
